const appname = "SUFIMART";
const appversion = "Version 1.0.0";
const credits = "@Sufyan Maqsood";
const email = "Email";
const emailHint = "abc@gmail.com";
const password = "Password";
const retypePassword = "Retype Password";
const retypePasswordHint = "********";
const name = "Name";
const nameHint = "User Name";
const passwordHint = "********";
const forgetPass = "Forget Password?";
const login = "Log in";
const logout = "Log out";
const signup = "Sign up";
const createNewAccount = "or, create a new account";
const loginWith = " Log in with";
const privacyPolicy = "Privacy Policy";
const termsAndCondition = "Terms and Conditions";
const alreadyHaveAccount = " Already have an account?";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
const searchAnyThing = "Search anything...",
    todayDeal = "Today's Deal",
    flashsale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Brand",
    topCategory = "Top Categories",
    featuredCategories = "Featured Categories",
    womenDress = "Women Dress",
    girlsWatches = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    tShirts = "TShirts",
    girlsDress = " Girls Dresses";
const featuredProducts = "Featured Products";
const womenFashion = "Women Fashion",
    menClothingFashion = "Men Clothing & Fashion",
    compAccess = "Computer & Accessories",
    automobile = "Automobile",
    kidstoys = "Kids & Toys",
    sports = "Sports",
    jewelery = "Jewelery",
    cellphone = "Cellphone & Tab",
    furniture = "Furniture";
// item details
const video = "Video",
    reviews = "Reviews",
    sellerpolicy = "Seller Policy",
    returnpolicy = "Return Policy",
    supportpolicy = "Support Policy",
    productyoumaylike = "Products you may also like";
const wishlist = "My Wishlist",
    orders = "My Orders",
    messages = "Messages",
    oldpass = "Old Password",
    newpass = "New Password";
const loggedin = "Logged in Successfully";
const loggedout = "Log out Successfully";
const paypal = "Paypal", stripe = "Stripe", cod = "Cash on delivery";
